name: Healthcheck

on:
  pull_request:
    branches:
      - main

jobs:
  healthcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/iron"

      - uses: actions/cache@v4
        id: yarn-cache
        env:
          YARN_ENABLE_GLOBAL_CACHE: true
          YARN_CACHE_FOLDER: $(yarn cache dir)
        with:
          path: ${{ env.YARN_CACHE_FOLDER }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Validate dependencies
        run: yarn install --immutable

      - name: Run healthcheck
        run: yarn healthcheck
